floooh/sokol-tools

src/shdc/sokol.cc

Looks like a c&p typo to me. Only noticeable if compiled without `--noifdef`.

fix sokol-gfx backend define

---

src/shdc/bare.cc
src/shdc/output.cc
src/shdc/shdc.h
src/shdc/sokol.cc

This breaks the existing output file format, but I couldn't think of a way to work around that.
With these changes the output filename will be: 
arg.output + mod_name + program_name + {_vs|_fs} + {ending}
_vs / _fs seemed to match existing naming in sokol better than .vert / .frag, but if you prefer to keep .vert/.frag I wouldn't mind changing it.

support for multiple shaders in same .glsl file for bare format

---

docs/sokol-shdc.md
src/shdc/input.cc

Fixes #24. I didn't put this behind a flag since I don't see the point in that, but am willing to if you'd prefer.

Allow writing standards-compliant-ish glsl by allowing tags to be prefixed by #pragma sokol

---

src/shdc/spirv.cc

shader debuggers (eg renderdoc) don't handle empty line # directives
Simple fix is to just set string names to basepath for the spirv emitter although sometimes it will still emit line directives pointing to the same line.
Another alternative is to disable debug info emission but opted to keep same behavior in case others rely on it

fix: shdc emits empty `line # ""` directives

---

build.zig

It seems the `build.zig` file is outdated: `output.cc` doesn't exist anymore, and `util.cc` should be included.

fix `build.zig`

---

src/shdc/args.cc
src/shdc/spirv.cc

`fmt::print()` expects the format argument to be consteval.

Fix consteval errors when compiling as C++20

---

docs/sokol-shdc.md

Looks like the actual keyword used has the 's' at the end, when I use the singular form I get a sokol-shdc error like:
./../cppsrc/opengl/programs/shaders/pole_cap_program.sokol:3:0: error: unknown meta tag: @msl_option

Fix spelling of keyword

---

src/shdc/bare.cc
src/shdc/shdc.h
src/shdc/util.cc

Generate yaml file info for bare format shaders. 
It can be useful if somebody wants to use sokol_shc on the fly or for using with another libraries other than sokol.
I attached an output sample for you to take a view.
[test_slm.txt](https://github.com/floooh/sokol-tools/files/9062155/test_slm.txt)
Please let me know if you need more info or any change requests.

Generate yaml info for bare format

---

src/shdc/sokolnim.cc

[nim binding](https://github.com/floooh/sokol-nim/blob/56bb1389fd265cebe72f04257446d78a356656ff/src/sokol/gfx.nim#L45C1-L54C18)
```nim
type
Backend* {.size:sizeof(int32).} = enum
backendGlcore33,
backendGles3,   # here
backendD3d11,
backendMetalIos,
backendMetalMacos,
backendMetalSimulator,
backendWgpu,
backendDummy,
```

There may be a typo here, there is only backendGles3 in the nim binding

---

CHANGELOG.md
src/shdc/spirvcross.cc
test/issue_109.glsl

Previously the output of the SPIRVCross HLSL/MSL/WGSL pass were used as input to the reflection parsing, which required to create dummy samplers, which in turn could lead to issues like https://github.com/floooh/sokol-tools/issues/109.
The new approach uses common SPIRVCross GLSL output for the reflection parsing (which doesn't require to deal with dummy samplers and seems to produce the correct output for parsing the reflection data - also leading to simpler code).

Fix/issue-109: Different approach to reflection parsing for HLSL, MSL, WGSL.

---

CHANGELOG.md
docs/sokol-shdc.md
src/shdc/args.cc
src/shdc/generators/generate.cc
src/shdc/generators/sokold.cc
src/shdc/generators/sokold.h
src/shdc/types/format.h

...rewrite of https://github.com/floooh/sokol-tools/pull/115 for the new code generator structure.

New attempt at D language generator.

---

src/shdc/types/reflection/storage_buffer.h

This bit me today while doing some experiments with the new storage buffer support :D
`StorageBuffer::Num == 4` while `SG_MAX_SHADERSTAGE_STORAGE_BUFFERS == 8`, causing the `sg_shader_desc` to not mark storage buffers `4..8` as used (and `sokol_gfx.h` to give a validation error) even when they compile just fine and are enumerated by the `*_storagebuffer_slot` reflection function. oops!

StorageBuffer::Num shold match SG_MAX_SHADERSTAGE_STORAGE_BUFFERS

---

CHANGELOG.md
src/shdc/generators/generator.cc
src/shdc/generators/generator.h
src/shdc/generators/sokolc.cc
src/shdc/generators/sokolc.h
src/shdc/generators/sokold.cc
src/shdc/generators/sokold.h
src/shdc/generators/sokolnim.cc
src/shdc/generators/sokolnim.h
src/shdc/generators/sokolodin.cc
src/shdc/generators/sokolodin.h
src/shdc/generators/sokolrust.cc
src/shdc/generators/sokolrust.h
src/shdc/generators/sokolzig.cc
src/shdc/generators/sokolzig.h
src/shdc/reflection.cc
src/shdc/reflection.h
src/shdc/types/reflection/stage_attr.h

Don't generate duplicate vertex attr defines/constants (fixes #133)

---

build.zig

This change updates `build.zig` so it works with Zig 0.13 by using the `b.path()` function to initialize `LazyPath`s. Apparently specifying paths with struct literals is no longer allowed? Or at least not with these struct literals.  This change also adds `sokold.cc` to a list of sources it was missing from, which was causing a link error.
I'm new to Zig, so it's possible there's a more idiomatic way to do this, but `b.path()` is what I've seen elsewhere.
I didn't see any tests for the Zig build, so I just smoke tested this change on my Mac: build the binary, run it on a few GLSL files from`test/`, make sure the output looks halfway reasonable.

Fix build.zig for Zig 0.13

---

build.zig
src/shdc/generators/sokoljai.cc

I noticed a lot of small issues with the initial PR that merged the code generator for Jai (ie: it doesn't compile), so i though i'd open a PR for the fixed since i've been using a private fork for a while.
The current version in master had invalid syntax so i'm assuming the author used the syntax of Odin (or another) and forgot to replace some of the things.
I compiled the SDF.glsl file from the samples to show the differences in output to save some time.
Most issues were `,` instead of `;` and struct padding issues and i also removed the `#scope_module` since that's the default.
I've a comment to explain why i don't think importing `sokol_gfx` is the right call at the moment, let me know what you think about this.
I also have generated the bindings for sokol, if that's something you'd …

Fix Jai code generator

---

src/shdc/generators/sokoljai.cc

the jai generator was missing a `{}` in uniform array_count, this fixes it.

fix array_count for jai generator

---

src/shdc/generators/yaml.cc
src/shdc/generators/yaml.h
src/shdc/reflection.cc

In some cases it's useful to be able to look at the layout of the actual unflattened uniform blocks, this adds access to that data to the `bare_yaml` output when the `--reflection` argument is used.
Example output:
```
uniform_blocks:
-
slot: 0
size: 144
struct_name: vs_params
inst_name: _19
uniforms:
-
name: vs_params
type: vec4
array_count: 9
offset: 0
uniform_blocks_refl:
-
slot: 0
size: 144
struct_name: vs_params
inst_name: _19
uniforms:
-
name: u_projViewMatrix
type: mat4
array_count: 0
offset: 0
-
name: u_modelMatrix
type: mat4
array_count: 0
offset: 64
-
name: u_color
type: vec4
array_count: 0
offset: 128
```

Generating bare_yaml output with the --reflection option includes unflattened uniform block data

---

src/shdc/generators/sokolzig.cc
src/shdc/generators/sokolzig.h

Example output for a program called 'default' looks like:
```
pub fn defaultAttrSlot(attr_name: []const u8) i32 {
if (std.mem.eql(u8, attr_name, "pos")) {
return 0;
}
if (std.mem.eql(u8, attr_name, "color0")) {
return 1;
}
if (std.mem.eql(u8, attr_name, "texcoord0")) {
return 2;
}
return -1;
}
pub fn defaultImageSlot(stage: sg.ShaderStage, img_name: []const u8) i32 {
if (sg.ShaderStage.FS == stage) {
if (std.mem.eql(u8, img_name, "tex")) {
return 0;
}
}
return -1;
}
pub fn defaultSamplerSlot(stage: sg.ShaderStage, smp_name: []const u8) i32 {
if (sg.ShaderStage.FS == stage) {
if (std.mem.eql(u8, smp_name, "smp")) {
return 0;
}
}
return -1;
}
pub fn defaultUniformblockSlot(stage: sg.ShaderStage, ub_name: []const u8) i32 {
if (sg.ShaderStage.VS == stage) {
if (std.mem.eql(u8, ub_name, …
```

Adding reflection functions to Zig output

---

src/shdc/generators/yaml.cc
src/shdc/reflection.cc
src/shdc/types/reflection/stage_attr.h

I don't know if this would be useful, but someone in the #gamedev channel on the Zig discord was talking about wanting to get the type of a vertex attribute and I saw that it wasn't being included yet, this adds some type info to the `StageAttr` struct and outputs the type in generated yaml files just to start.

Adding the type to Vertex Attributes in the bare yaml reflection

---

src/shdc/generators/sokolnim.cc

A Nim project was failing to compile using shaders produced for the wgsl backend, so I believe this will do the trick!

change backendWgsl to correct name backendWgpu in Nim generator

---

build.zig
src/shdc/args.cc
src/shdc/generators/generate.cc
src/shdc/generators/sokolc3.cc
src/shdc/generators/sokolc3.h
src/shdc/types/format.h

Not yet finished version of C3 generator. I'm using it for examples in sokol-c3 repo.
This will accompany https://github.com/floooh/sokol/pull/1148

[WIP] Add support for C3 language

---

README.md

Fixes a mistake in the Readme regarding how to build on linux.
```
cd docker/
./build.sh
```
There is no docker/ folder and the build script is just ./build_docker.sh.

Fix error in readme.

---

.github/workflows/build.yml
.github/workflows/deploy.yml
Dockerfile

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
cc: @floooh

CI: Linux arm64

---

src/shdc/generators/sokolc.cc

Fix for #167
changes `sg_shader_uniform_desc` -> `sg_glsl_shader_uniform` in C header reflection forward decls.

Update sokolc.cc gen_prerequisites for bindings cleanup (fix for #167)

---

CHANGELOG.md
src/shdc/reflection.cc
src/shdc/spirvcross.cc
src/shdc/types/reflection/bindings.h

...instead use the original bindings from 0..7 across all shader stages. This allows compatibility with lower end GL drivers which only support 8 storage buffers.

GLSL output: don't remap storage buffer bindings to 0..16

---

src/shdc/generators/sokolodin.cc
src/shdc/generators/sokolodin.h

Fixes #171
Was pretty straightforward, but is my first time writing cpp so let me know if I committed any code-crimes 😅
Test Shader:
```glsl
@header package shaders
@header import sg "../../sokol/gfx"
@ctype mat4 matrix[4,4]f32
// -------- UNIFORMS
@block uniforms
layout(binding=0) uniform vs_uniforms {
mat4 mvp;
};
@end
// -------- TEXTURED SHADER
@vs vs_textured
@include_block uniforms
in vec3 vert_position;
in vec4 vert_color;
in vec2 vert_uv;
out vec4 color;
out vec2 uv;
void main() {
gl_Position = mvp * vec4(vert_position, 1.0);
color = vert_color;
uv = vert_uv;
}
@end
@fs fs_textured
layout(binding=0) uniform texture2D tex;
layout(binding=0) uniform sampler smp;
in vec4 color;
in vec2 uv;
out vec4 frag_color;
void main() {
frag_color = texture(sampler2D(tex, smp), uv) * color;
} …
```

Fix: Added Odin support for reflection flag and module tag (#171)

---

CHANGELOG.md
src/shdc/generators/generator.h
src/shdc/generators/sokolc.cc
src/shdc/generators/sokolc.h
src/shdc/generators/sokolc3.cc
src/shdc/generators/sokolc3.h
src/shdc/generators/sokold.cc
src/shdc/generators/sokold.h
src/shdc/generators/sokoljai.cc
src/shdc/generators/sokoljai.h
src/shdc/generators/sokolnim.cc
src/shdc/generators/sokolnim.h
src/shdc/generators/sokolodin.cc
src/shdc/generators/sokolodin.h
src/shdc/generators/sokolrust.cc
src/shdc/generators/sokolrust.h
src/shdc/generators/sokolzig.cc
src/shdc/generators/sokolzig.h
src/shdc/generators/yaml.cc
src/shdc/generators/yaml.h
src/shdc/types/reflection/type.h

(also cleans up some redundant semicolons that slipped in during the compute shader update)
Associated sokol-gfx PR: https://github.com/floooh/sokol/pull/1222
TODO:

Extract vertex attribute base type into code-generated sg_shader_desc.

---

src/shdc/generators/sokoljai.cc

The current shader compiler creates Jai files with #align next to the struct, this doesn't compile and is invalid syntax with the newest Jai beta compiler (and has maybe never compiled?). This PR attempts to fix the situation and I tested that the generated syntax compiles.

fix: incorrect align syntax for Jai
